import os
from dotenv import load_dotenv
load_dotenv()
BOT_TOKEN = os.getenv("BOT_TOKEN")
PROXY_URL = os.getenv("PROXY_URL")
PROXY_REQUEST_TIME_OUT = os.getenv("PROXY_REQUEST_TIME_OUT")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_USERNAME = os.getenv("REDIS_USER")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_PORT = os.getenv("REDIS_PORT")
GRADE_A_OFF = os.getenv("GRADE_A_OFF")
GRADE_B_OFF = os.getenv("GRADE_B_OFF")
GRADE_C_OFF = os.getenv("GRADE_C_OFF")
GRADE_S_OFF = os.getenv("GRADE_S_OFF")
PRODUCT_IDS_A = os.getenv("PRODUCT_IDS_A")
PRODUCT_IDS_B = os.getenv("PRODUCT_IDS_B")
PRODUCT_IDS_C = os.getenv("PRODUCT_IDS_C")
PRODUCT_IDS_S = os.getenv("PRODUCT_IDS_S")
WEBSITE_API_URL = os.getenv("WEBSITE_API_URL")
WEBSITE_API_KEY = os.getenv("WEBSITE_API_KEY")
EXAM_DURATION_SECONDS = int(os.getenv("EXAM_DURATION_SECONDS"))